import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNavBar from "@/components/navigation/TopNavBar";
import SideNavBar from "@/components/navigation/SideNavBar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 3600 // revalidate at most every hour
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-screen grid grid-cols-12 gap-4 relative isolate")}>
        <nav className="sticky top-0 bg-slate-100/50 backdrop-blur-lg shadow z-50 h-auto col-start-1 col-end-13">
          <TopNavBar />
        </nav>

        <div className="col-start-1 col-end-4 row-start-2 bg-gray-100 sticky left-0 top-[10%] h-screen">
          <SideNavBar />
        </div>

        <main className="min-h-screen relative col-start-4 col-end-13 row-start-2">
          {children}
        </main>
      </body>
    </html>
  );
}
